// @ts-nocheck
import { createServer } from "miragejs";

export const backendCreateServer = () =>
  createServer({
    routes() {
      this.namespace = "api";
      this.timing = 0;

      this.get("/films", {
        page: 1,
        results: [
          {
            adult: false,
            backdrop_path: "/hziiv14OpD73u9gAak4XDDfBKa2.jpg",
            genre_ids: [12, 14],
            id: 671,
            original_language: "en",
            original_title: "Harry Potter and the Philosopher's Stone",
            overview:
              "Harry Potter dowiaduje się, w dniu swoich 11-tych urodzin, że jest osieroconym dzieckiem dwojga potężnych czarodziejów i sam posiada magiczne zdolności. W Szkole Magii i Czarodziejstwa w Hogwarcie przeżywa największą przygodę swojego życia. Uczy się latania na miotle i różnych pożytecznych zaklęć. Przeżywa także chwile grozy rozwiązując zagadkę tajemniczego kamienia filozoficznego i tocząc walkę z potężnym i złym czarodziejem-Lordem Voldermort.",
            popularity: 178.689,
            poster_path: "/lz1qjw1wDbE2Kj76iTXpGKQSPKD.jpg",
            release_date: "2001-11-16",
            title: "Harry Potter i Kamień Filozoficzny",
            video: false,
            vote_average: 7.9,
            vote_count: 19293,
          },
          {
            adult: false,
            backdrop_path: "/8f9dnOtpArDrOMEylpSN9Sc6fuz.jpg",
            genre_ids: [12, 14, 10751],
            id: 674,
            original_language: "en",
            original_title: "Harry Potter and the Goblet of Fire",
            overview:
              "W Hogwarcie rozgrywa się Turniej Trójmagiczny, na który przybywają uczniowie szkół z Francji i Bułgarii. Zgodnie ze starą tradycją, do turnieju mają być wybrani trzej przedstawiciele, każdej ze szkół. Jednak dziwnym zbiegiem okoliczności do turnieju zostaje wybranych czterech uczestników, w tym i Harry Potter. Odtąd na głównego bohatera czekają trzy zadania, a w związku z nimi wiele niesamowitych i niebezpiecznych przygód.",
            popularity: 158.576,
            poster_path: "/kRGddmzmxXcFZsJcEqVlgXUb29S.jpg",
            release_date: "2005-11-16",
            title: "Harry Potter i Czara Ognia",
            video: false,
            vote_average: 7.8,
            vote_count: 14811,
          },
          {
            adult: false,
            backdrop_path: "/kT8bDEAgEYBKhRJtqM97qTw6uRW.jpg",
            genre_ids: [12, 14],
            id: 767,
            original_language: "en",
            original_title: "Harry Potter and the Half-Blood Prince",
            overview:
              "Lord Voldemort zaciska swoją złowieszczą pętlę wokół świata Mugoli i czarodziejów, a Hogwart przestaje być – jak dawniej - bezpieczną przystanią. Harry podejrzewa, że niebezpieczeństwo może czaić się w samym zamku, ale Dumbledorowi zależy raczej na przygotowaniu go do ostatecznego starcia, które jego zdaniem nastąpi niebawem. Razem usiłują znaleźć broń zdolną skruszyć zapory Voldemorta. Harry’emu coraz bardziej podoba się Ginny...niestety, Dean Thomas jest nią również zainteresowany. Lavender Brown dochodzi do wniosku, że Ron jest jej przeznaczeniem, nie bierze tylko pod uwagę czekoladek Romildy Vane! No i oczywiście Hermiona, przeżywająca męki zazdrości, lecz zdecydowana nie ujawniać uczuć. Gdy romanse kwitną, tylko jeden uczeń pozostaje wyniosły i obojętny. Postanowił wywrzeć swoje niezatarte – choć mroczne – piętno na życiu Akademii. Miłość wisi w powietrzu, lecz za nią czai się dramat i Hogwart być może już nigdy nie będzie taki jak przedtem.",
            popularity: 131.415,
            poster_path: "/z7uo9zmQdQwU5ZJHFpv2Upl30i1.jpg",
            release_date: "2009-07-07",
            title: "Harry Potter i Książę Półkrwi",
            video: false,
            vote_average: 7.7,
            vote_count: 13981,
          },
          {
            adult: false,
            backdrop_path: "/1stUIsjawROZxjiCMtqqXqgfZWC.jpg",
            genre_ids: [12, 14],
            id: 672,
            original_language: "en",
            original_title: "Harry Potter and the Chamber of Secrets",
            overview:
              "Harry powraca do Hogwartu, aby ponownie zmierzyć się z niebezpieczeństwem tym razem zagrażającym także jego najlepszej przyjaciółce. Podczas drugiego roku pobytu w Szkole Magii i Czarodziejststwa młody Potter spotyka starych wrogów, poznaje nowego nauczyciela, odkrywa w sobie nowe zdolności, unika śmierci z rąk domowego skrzata chcącego za wszelką cenę uratować mu życie i wraz z dwójką swoich przyjaciół: Ronem i Hermioną znów udaje mu się rozwiązać trudną zagadkę.",
            popularity: 143.37,
            poster_path: "/csOv5H7R2zdnKaYuTrGVWohmo8d.jpg",
            release_date: "2002-11-13",
            title: "Harry Potter i Komnata Tajemnic",
            video: false,
            vote_average: 7.7,
            vote_count: 15738,
          },
          {
            adult: false,
            backdrop_path: "/vbk5CfaAHOjQPSAcYm6AoRRz2Af.jpg",
            genre_ids: [12, 14],
            id: 673,
            original_language: "en",
            original_title: "Harry Potter and the Prisoner of Azkaban",
            overview:
              "Harry Potter i jego najlepsi przyjaciele Ron i Hermiona, po przerwie letniej powracają do Hogwartu, aby rozpocząć trzeci rok nauki. W tym samym czasie z pilnie strzeżonego więzienia dla czarodziejów ucieka niebezpieczny przestępca - Syriusz Black! Wszystko wskazuję na to, że Black poluje na Harrego. Cały świat czarodziejów rozpoczyna poszukiwania zbiega; z Azkabanu zostają wysłane przerażające istoty - Dementorzy, w celu zabicia przestępcy.",
            popularity: 143.484,
            poster_path: "/v0wMKEEGaNc9evdqGYfIvoWXh24.jpg",
            release_date: "2004-05-31",
            title: "Harry Potter i więzień Azkabanu",
            video: false,
            vote_average: 8,
            vote_count: 15449,
          },
          {
            adult: false,
            backdrop_path: "/pkxPkHOPJjOvzfQOclANEBT8OfK.jpg",
            genre_ids: [12, 14, 9648],
            id: 675,
            original_language: "en",
            original_title: "Harry Potter and the Order of the Phoenix",
            overview:
              "Harry Potter tym razem nie może mieć spokojnych wakacji. Lord Voldemort powrócił, a prasa czarodziejska milczy na ten temat. Na mugolskim osiedlu Little Whinging pojawiają się Dementorzy, a zbzikowana sąsiadka Dursley'ów pani Figg jest charłakiem! W dodatku Harry staje przed całym Wizengamotem za użycie czarów przez nieletniego, a Straż Przednia zabiera go do kwatery głównej Zakonu Feniksa - organizacji powołanej przez Dumbledora do walki z Sam-Wiesz-Kim. Tymczasem w Hogwarcie rządy przejmuje sprzymierzeniec Korneliusza Knota i nauczycielka obrony przed czarną magią profesor Umbridge. Wygląda na to, że nikt nie wierzy Harry'emu i Dumbledorowi, że Lord Voldemort odrodził się na nowo. Kiedy zaatakuje wszystko wyjdzie na jaw, ale czy wtedy nie będzie już za późno?",
            popularity: 123.219,
            poster_path: "/g6n8G0xPnBVUIKKK41sNmbZB5h4.jpg",
            release_date: "2007-06-28",
            title: "Harry Potter i Zakon Feniksa",
            video: false,
            vote_average: 7.7,
            vote_count: 14200,
          },
          {
            adult: false,
            backdrop_path: "/n5A7brJCjejceZmHyujwUTVgQNC.jpg",
            genre_ids: [14, 12],
            id: 12445,
            original_language: "en",
            original_title: "Harry Potter and the Deathly Hallows: Part 2",
            overview:
              "W drugiej części widowiskowego zakończenia serii walka sił dobra z siłami zła świata czarodziejów przeistacza się w otwartą wojnę. Stawka nigdy nie była tak wysoka; nikt nie może czuć się bezpieczny. Być może w trakcie nieuchronnie zbliżającej się ostatecznej rozgrywki z Lordem Voldemortem to Harry Potter będzie zmuszony do ostatecznego poświęcenia. Tak kończy się cała opowieść.",
            popularity: 131.772,
            poster_path: "/da22ZBmrDOXOCDRvr8Gic8ldhv4.jpg",
            release_date: "2011-07-07",
            title: "Harry Potter i Insygnia Śmierci: Część II",
            video: false,
            vote_average: 8.1,
            vote_count: 15035,
          },
          {
            adult: false,
            backdrop_path: "/AqLcLsGGTzAjm3pCCq0CZCQrp6m.jpg",
            genre_ids: [12, 14],
            id: 12444,
            original_language: "en",
            original_title: "Harry Potter and the Deathly Hallows: Part 1",
            overview:
              "Harry, Ron i Hermiona wyruszają z niebezpieczną misją, by odnaleźć i zniszczyć horkruksy, w których tkwi tajemnica siły Voldemorta. Zdani tylko na siebie, ścigani teraz bardziej niż kiedykolwiek, mogą polegać tylko na sobie, a Siły Ciemności, które są blisko, próbują ich rozdzielić.",
            popularity: 117.334,
            poster_path: "/iGoXIpQb7Pot00EEdwpwPajheZ5.jpg",
            release_date: "2010-10-17",
            title: "Harry Potter i Insygnia Śmierci: Część I",
            video: false,
            vote_average: 7.8,
            vote_count: 13993,
          },
          {
            adult: false,
            backdrop_path: "/22esNAKvdcHaeyzhXD5uhTjDwTK.jpg",
            genre_ids: [28, 80, 53],
            id: 984,
            original_language: "en",
            original_title: "Dirty Harry",
            overview:
              "W swojej sztandarowej roli Clint Eastwood wcielił się w postać przebiegłego policyjnego detektywa z San Francisco, który jest najlepszy w tym co robi. Bezwzględny snajper Scorpio (Andrew Robinson) zabił już dwoje niewinnych ludzi. Harry Callahan zamierza się nim zająć... w taki czy inny sposób... bez względu na przepisy.",
            popularity: 22.877,
            poster_path: "/cr0nai1uS8Qyc3zoirMIj8wzhM9.jpg",
            release_date: "1971-07-14",
            title: "Brudny Harry",
            video: false,
            vote_average: 7.5,
            vote_count: 1485,
          },
          {
            adult: false,
            backdrop_path: "/AhmRmdlu7GYdiucfZzVCGyP8ICf.jpg",
            genre_ids: [53, 80, 18, 28],
            id: 25941,
            original_language: "en",
            original_title: "Harry Brown",
            overview:
              "Dynamiczny film o krwawej zemście w stylu „Uprowadzonej”. Miasto, w którym mieszka Harry Brown (Michael Caine), były żołnierz piechoty morskiej, pogrąża się we wszechogarniającej przemocy. Grupy chuliganów atakują przechodniów i wprowadzają terror. Tego stanu rzeczy nie może znieść Leonard, przyjaciel Harry’ego. Podczas próby powstrzymania bandytów dochodzi do bójki i mężczyzna zostaje zabity. Zatrzymani za morderstwo młodzi przestępcy zostają jednak wypuszczeni przez policję na wolność. Harry bierze sprawy w swoje ręce. Bandytów czeka bezlitosna zemsta.",
            popularity: 10.949,
            poster_path: "/tHynkXrurd8qL57fbP5xVpKDh1l.jpg",
            release_date: "2009-11-11",
            title: "Harry Brown",
            video: false,
            vote_average: 6.8,
            vote_count: 662,
          },
          {
            adult: false,
            backdrop_path: "/cXU4zg2aKglQrMOLokHLbnxwkGV.jpg",
            genre_ids: [35, 10749, 18],
            id: 639,
            original_language: "en",
            original_title: "When Harry Met Sally...",
            overview:
              "Historia dwunastoletniego związku dwojga młodych ludzi, których drogi po skończeniu studiów rozchodzą się. Po pięciu latach przypadkowo spotykają się w samolocie. Początkowa niechęć z wolna przeobraża się w przyjaźń. Po wielu wspólnie spędzonych chwilach ciężko jest im stwierdzić czy dalej są tylko przyjaciółmi, czy łączy ich coś więcej.",
            popularity: 17.209,
            poster_path: "/t7vXcgNGnZ8czPov0UkQI7o3QRn.jpg",
            release_date: "1989-01-12",
            title: "Kiedy Harry poznał Sally",
            video: false,
            vote_average: 7.4,
            vote_count: 2709,
          },
          {
            adult: false,
            backdrop_path: "/4LOxoeZWt5wr9mooxEZRFK96lDd.jpg",
            genre_ids: [99],
            id: 483898,
            original_language: "en",
            original_title: "50 Greatest Harry Potter Moments",
            overview: "",
            popularity: 46.37,
            poster_path: "/g1xiBoLD6v3ZaXPa4QtuXiQeYKW.jpg",
            release_date: "2011-07-27",
            title: "50 Greatest Harry Potter Moments",
            video: false,
            vote_average: 7.8,
            vote_count: 22,
          },
          {
            adult: false,
            backdrop_path: "/coJLkvK5KZQoMl8vGqcpgAZYroi.jpg",
            genre_ids: [35, 18],
            id: 2639,
            original_language: "en",
            original_title: "Deconstructing Harry",
            overview: "",
            popularity: 9.837,
            poster_path: "/2ZkTBt5wunAIIEx6UFtxxLdzkKM.jpg",
            release_date: "1997-12-12",
            title: "Przejrzeć Harry'ego",
            video: false,
            vote_average: 7.4,
            vote_count: 532,
          },
          {
            adult: false,
            backdrop_path: "/hNQ0R4wSaXTUPUQti8FtKLf1HQ6.jpg",
            genre_ids: [35, 80, 9648],
            id: 11718,
            original_language: "en",
            original_title: "Who's Harry Crumb?",
            overview:
              "Harry Crumb należy do największej rodziny prywatnych detektywów. Niestety, przez niezdarność został z niej wyrzucony na 10 lat. W tym czasie interes został przejęty przez Eliota Draisena. Gdy Harry powraca, Eliot zleca mu sprawę porwanego dziecka. Robi to, by móc uciec z żoną klienta. Za pomocą przebrań Harry chce rozwiązać sprawę i udowodnić, że należy do rodziny Crumbów.",
            popularity: 9.261,
            poster_path: "/qf7LNguEfBHF9WRs9sKGPBaQYEt.jpg",
            release_date: "1989-02-03",
            title: "Kim jest Harry Crumb?",
            video: false,
            vote_average: 5.7,
            vote_count: 178,
          },
          {
            adult: false,
            backdrop_path: "/71gHxSX2Tzg9mi1VYRdwCECfmpj.jpg",
            genre_ids: [35, 14, 10751],
            id: 8989,
            original_language: "en",
            original_title: "Harry and the Hendersons",
            overview:
              "George, Nancy oraz ich dzieci, Sarah i Ernie, wracają samochodem z wakacji. Przejeżdżając przez las, potrącają na szosie wielkie, kudłate zwierzę. Przekonani, że stworzenie jest martwe, przywożą je do domu, by powiadomić o wypadku nadleśnictwo. Wkrótce okazuje się, że stwór żyje i szybko wraca do sił. Hendersonowie przywiązują się do łagodnej istoty, której nadają imię Harry. Pewnego dnia olbrzym ucieka. W mieście wybucha panika. Hendersonowie próbują za wszelką cenę uratować włochatego przyjaciela, którego ściga myśliwy.",
            popularity: 10.607,
            poster_path: "/7bmtLtiei9WLe8wY8hKk1Smf65z.jpg",
            release_date: "1987-06-05",
            title: "Harry i Hendersonowie",
            video: false,
            vote_average: 5.9,
            vote_count: 426,
          },
          {
            adult: false,
            backdrop_path: "/nKM71iyHoXG2DUBXml0mNwPChvg.jpg",
            genre_ids: [10749, 10770, 35],
            id: 647325,
            original_language: "en",
            original_title: "The Thing About Harry",
            overview: "",
            popularity: 14.686,
            poster_path: "/sdn5NdFMcsub3QUwlovOA9fPJoW.jpg",
            release_date: "2020-02-15",
            title: "The Thing About Harry",
            video: false,
            vote_average: 7.9,
            vote_count: 88,
          },
          {
            adult: false,
            backdrop_path: "/bDqchWjPhko0XvRBx4pErPMk0Hv.jpg",
            genre_ids: [10749],
            id: 518527,
            original_language: "en",
            original_title: "Harry & Meghan: A Royal Romance",
            overview: "",
            popularity: 13.107,
            poster_path: "/2ODzSaM8EKF28mGjNTH3ptb3BJu.jpg",
            release_date: "2018-05-13",
            title: "Harry & Meghan: A Royal Romance",
            video: false,
            vote_average: 6.9,
            vote_count: 150,
          },
          {
            adult: false,
            backdrop_path: "/kagW7NjLnnWzF7BFX8CfNUobQWM.jpg",
            genre_ids: [18, 10749],
            id: 27091,
            original_language: "en",
            original_title: "Harry + Max",
            overview: "",
            popularity: 5.998,
            poster_path: "/nIamsnmqYgRLuosJFlWGiCMXS8A.jpg",
            release_date: "2004-01-17",
            title: "Harry + Max",
            video: false,
            vote_average: 5.6,
            vote_count: 18,
          },
          {
            adult: false,
            backdrop_path: "/eAPj43jprYqhQvqzaP7B1LL7B0N.jpg",
            genre_ids: [12, 35, 18, 10749],
            id: 42448,
            original_language: "en",
            original_title: "Harry and Tonto",
            overview: "",
            popularity: 5.275,
            poster_path: "/5aCrpRRJJBPZ0QqNuMmW2Rzp9FQ.jpg",
            release_date: "1974-08-12",
            title: "Harry and Tonto",
            video: false,
            vote_average: 7.1,
            vote_count: 51,
          },
          {
            adult: false,
            backdrop_path: "/4PHbeHC7q7XJk44TsbAUwDS2rv1.jpg",
            genre_ids: [18],
            id: 91767,
            original_language: "en",
            original_title: "Harry & Son",
            overview:
              "Harry (Paul Newman), mężczyzna w średnim wieku, ma duże problemy z komunikacją ze swym nastoletnim synem, Howardem (Robby Benson). Podczas gdy Harry chce, aby Howard znalazł sobie pracę i zarabiał na swoje życie, wrażliwy chłopak woli wybrać karierę pisarską. Howard stara się przekonac ojca do własnej decyzji, ale dochodzi do wniosku, że musi sam wziąć się za własne życie. W dodatku jego dziewczyna zachodzi w ciążę...",
            popularity: 5.058,
            poster_path: "/kl9yUlWRBEyXNGIXav1WIRBy5te.jpg",
            release_date: "1984-03-02",
            title: "Harry i syn",
            video: false,
            vote_average: 6.1,
            vote_count: 39,
          },
        ],
        total_pages: 22,
        total_results: 434,
      });
    },
  });
