// @ts-nocheck
import { createServer } from "miragejs";

export const backendCreateServer = () =>
  createServer({
    routes() {
      this.namespace = "api";
      this.timing = 0;

      this.get("/films", {
        page: 1,
        results: [
          {
            adult: false,
            backdrop_path: "/hziiv14OpD73u9gAak4XDDfBKa2.jpg",
            genre_ids: [12, 14],
            id: 671,
            original_language: "en",
            original_title: "Harry Potter and the Philosopher's Stone",
            overview:
              "Harry Potter dowiaduje się, w dniu swoich 11-tych urodzin, że jest osieroconym dzieckiem dwojga potężnych czarodziejów i sam posiada magiczne zdolności. W Szkole Magii i Czarodziejstwa w Hogwarcie przeżywa największą przygodę swojego życia. Uczy się latania na miotle i różnych pożytecznych zaklęć. Przeżywa także chwile grozy rozwiązując zagadkę tajemniczego kamienia filozoficznego i tocząc walkę z potężnym i złym czarodziejem-Lordem Voldermort.",
            popularity: 178.689,
            poster_path: "/lz1qjw1wDbE2Kj76iTXpGKQSPKD.jpg",
            release_date: "2001-11-16",
            title: "Harry Potter i Kamień Filozoficzny",
            video: false,
            vote_average: 7.9,
            vote_count: 19293,
          },
          {
            adult: false,
            backdrop_path: "/8f9dnOtpArDrOMEylpSN9Sc6fuz.jpg",
            genre_ids: [12, 14, 10751],
            id: 674,
            original_language: "en",
            original_title: "Harry Potter and the Goblet of Fire",
            overview:
              "W Hogwarcie rozgrywa się Turniej Trójmagiczny, na który przybywają uczniowie szkół z Francji i Bułgarii. Zgodnie ze starą tradycją, do turnieju mają być wybrani trzej przedstawiciele, każdej ze szkół. Jednak dziwnym zbiegiem okoliczności do turnieju zostaje wybranych czterech uczestników, w tym i Harry Potter. Odtąd na głównego bohatera czekają trzy zadania, a w związku z nimi wiele niesamowitych i niebezpiecznych przygód.",
            popularity: 158.576,
            poster_path: "/kRGddmzmxXcFZsJcEqVlgXUb29S.jpg",
            release_date: "2005-11-16",
            title: "Harry Potter i Czara Ognia",
            video: false,
            vote_average: 7.8,
            vote_count: 14811,
          },
          {
            adult: false,
            backdrop_path: "/kT8bDEAgEYBKhRJtqM97qTw6uRW.jpg",
            genre_ids: [12, 14],
            id: 767,
            original_language: "en",
            original_title: "Harry Potter and the Half-Blood Prince",
            overview:
              "Lord Voldemort zaciska swoją złowieszczą pętlę wokół świata Mugoli i czarodziejów, a Hogwart przestaje być – jak dawniej - bezpieczną przystanią. Harry podejrzewa, że niebezpieczeństwo może czaić się w samym zamku, ale Dumbledorowi zależy raczej na przygotowaniu go do ostatecznego starcia, które jego zdaniem nastąpi niebawem. Razem usiłują znaleźć broń zdolną skruszyć zapory Voldemorta. Harry’emu coraz bardziej podoba się Ginny...niestety, Dean Thomas jest nią również zainteresowany. Lavender Brown dochodzi do wniosku, że Ron jest jej przeznaczeniem, nie bierze tylko pod uwagę czekoladek Romildy Vane! No i oczywiście Hermiona, przeżywająca męki zazdrości, lecz zdecydowana nie ujawniać uczuć. Gdy romanse kwitną, tylko jeden uczeń pozostaje wyniosły i obojętny. Postanowił wywrzeć swoje niezatarte – choć mroczne – piętno na życiu Akademii. Miłość wisi w powietrzu, lecz za nią czai się dramat i Hogwart być może już nigdy nie będzie taki jak przedtem.",
            popularity: 131.415,
            poster_path: "/z7uo9zmQdQwU5ZJHFpv2Upl30i1.jpg",
            release_date: "2009-07-07",
            title: "Harry Potter i Książę Półkrwi",
            video: false,
            vote_average: 7.7,
            vote_count: 13981,
          },
          {
            adult: false,
            backdrop_path: "/1stUIsjawROZxjiCMtqqXqgfZWC.jpg",
            genre_ids: [12, 14],
            id: 672,
            original_language: "en",
            original_title: "Harry Potter and the Chamber of Secrets",
            overview:
              "Harry powraca do Hogwartu, aby ponownie zmierzyć się z niebezpieczeństwem tym razem zagrażającym także jego najlepszej przyjaciółce. Podczas drugiego roku pobytu w Szkole Magii i Czarodziejststwa młody Potter spotyka starych wrogów, poznaje nowego nauczyciela, odkrywa w sobie nowe zdolności, unika śmierci z rąk domowego skrzata chcącego za wszelką cenę uratować mu życie i wraz z dwójką swoich przyjaciół: Ronem i Hermioną znów udaje mu się rozwiązać trudną zagadkę.",
            popularity: 143.37,
            poster_path: "/csOv5H7R2zdnKaYuTrGVWohmo8d.jpg",
            release_date: "2002-11-13",
            title: "Harry Potter i Komnata Tajemnic",
            video: false,
            vote_average: 7.7,
            vote_count: 15738,
          },
          {
            adult: false,
            backdrop_path: "/vbk5CfaAHOjQPSAcYm6AoRRz2Af.jpg",
            genre_ids: [12, 14],
            id: 673,
            original_language: "en",
            original_title: "Harry Potter and the Prisoner of Azkaban",
            overview:
              "Harry Potter i jego najlepsi przyjaciele Ron i Hermiona, po przerwie letniej powracają do Hogwartu, aby rozpocząć trzeci rok nauki. W tym samym czasie z pilnie strzeżonego więzienia dla czarodziejów ucieka niebezpieczny przestępca - Syriusz Black! Wszystko wskazuję na to, że Black poluje na Harrego. Cały świat czarodziejów rozpoczyna poszukiwania zbiega; z Azkabanu zostają wysłane przerażające istoty - Dementorzy, w celu zabicia przestępcy.",
            popularity: 143.484,
            poster_path: "/v0wMKEEGaNc9evdqGYfIvoWXh24.jpg",
            release_date: "2004-05-31",
            title: "Harry Potter i więzień Azkabanu",
            video: false,
            vote_average: 8,
            vote_count: 15449,
          },
          {
            adult: false,
            backdrop_path: "/pkxPkHOPJjOvzfQOclANEBT8OfK.jpg",
            genre_ids: [12, 14, 9648],
            id: 675,
            original_language: "en",
            original_title: "Harry Potter and the Order of the Phoenix",
            overview:
              "Harry Potter tym razem nie może mieć spokojnych wakacji. Lord Voldemort powrócił, a prasa czarodziejska milczy na ten temat. Na mugolskim osiedlu Little Whinging pojawiają się Dementorzy, a zbzikowana sąsiadka Dursley'ów pani Figg jest charłakiem! W dodatku Harry staje przed całym Wizengamotem za użycie czarów przez nieletniego, a Straż Przednia zabiera go do kwatery głównej Zakonu Feniksa - organizacji powołanej przez Dumbledora do walki z Sam-Wiesz-Kim. Tymczasem w Hogwarcie rządy przejmuje sprzymierzeniec Korneliusza Knota i nauczycielka obrony przed czarną magią profesor Umbridge. Wygląda na to, że nikt nie wierzy Harry'emu i Dumbledorowi, że Lord Voldemort odrodził się na nowo. Kiedy zaatakuje wszystko wyjdzie na jaw, ale czy wtedy nie będzie już za późno?",
            popularity: 123.219,
            poster_path: "/g6n8G0xPnBVUIKKK41sNmbZB5h4.jpg",
            release_date: "2007-06-28",
            title: "Harry Potter i Zakon Feniksa",
            video: false,
            vote_average: 7.7,
            vote_count: 14200,
          },
          {
            adult: false,
            backdrop_path: "/n5A7brJCjejceZmHyujwUTVgQNC.jpg",
            genre_ids: [14, 12],
            id: 12445,
            original_language: "en",
            original_title: "Harry Potter and the Deathly Hallows: Part 2",
            overview:
              "W drugiej części widowiskowego zakończenia serii walka sił dobra z siłami zła świata czarodziejów przeistacza się w otwartą wojnę. Stawka nigdy nie była tak wysoka; nikt nie może czuć się bezpieczny. Być może w trakcie nieuchronnie zbliżającej się ostatecznej rozgrywki z Lordem Voldemortem to Harry Potter będzie zmuszony do ostatecznego poświęcenia. Tak kończy się cała opowieść.",
            popularity: 131.772,
            poster_path: "/da22ZBmrDOXOCDRvr8Gic8ldhv4.jpg",
            release_date: "2011-07-07",
            title: "Harry Potter i Insygnia Śmierci: Część II",
            video: false,
            vote_average: 8.1,
            vote_count: 15035,
          },
          {
            adult: false,
            backdrop_path: "/AqLcLsGGTzAjm3pCCq0CZCQrp6m.jpg",
            genre_ids: [12, 14],
            id: 12444,
            original_language: "en",
            original_title: "Harry Potter and the Deathly Hallows: Part 1",
            overview:
              "Harry, Ron i Hermiona wyruszają z niebezpieczną misją, by odnaleźć i zniszczyć horkruksy, w których tkwi tajemnica siły Voldemorta. Zdani tylko na siebie, ścigani teraz bardziej niż kiedykolwiek, mogą polegać tylko na sobie, a Siły Ciemności, które są blisko, próbują ich rozdzielić.",
            popularity: 117.334,
            poster_path: "/iGoXIpQb7Pot00EEdwpwPajheZ5.jpg",
            release_date: "2010-10-17",
            title: "Harry Potter i Insygnia Śmierci: Część I",
            video: false,
            vote_average: 7.8,
            vote_count: 13993,
          },
          {
            adult: false,
            backdrop_path: "/22esNAKvdcHaeyzhXD5uhTjDwTK.jpg",
            genre_ids: [28, 80, 53],
            id: 984,
            original_language: "en",
            original_title: "Dirty Harry",
            overview:
              "W swojej sztandarowej roli Clint Eastwood wcielił się w postać przebiegłego policyjnego detektywa z San Francisco, który jest najlepszy w tym co robi. Bezwzględny snajper Scorpio (Andrew Robinson) zabił już dwoje niewinnych ludzi. Harry Callahan zamierza się nim zająć... w taki czy inny sposób... bez względu na przepisy.",
            popularity: 22.877,
            poster_path: "/cr0nai1uS8Qyc3zoirMIj8wzhM9.jpg",
            release_date: "1971-07-14",
            title: "Brudny Harry",
            video: false,
            vote_average: 7.5,
            vote_count: 1485,
          },
          {
            adult: false,
            backdrop_path: "/AhmRmdlu7GYdiucfZzVCGyP8ICf.jpg",
            genre_ids: [53, 80, 18, 28],
            id: 25941,
            original_language: "en",
            original_title: "Harry Brown",
            overview:
              "Dynamiczny film o krwawej zemście w stylu „Uprowadzonej”. Miasto, w którym mieszka Harry Brown (Michael Caine), były żołnierz piechoty morskiej, pogrąża się we wszechogarniającej przemocy. Grupy chuliganów atakują przechodniów i wprowadzają terror. Tego stanu rzeczy nie może znieść Leonard, przyjaciel Harry’ego. Podczas próby powstrzymania bandytów dochodzi do bójki i mężczyzna zostaje zabity. Zatrzymani za morderstwo młodzi przestępcy zostają jednak wypuszczeni przez policję na wolność. Harry bierze sprawy w swoje ręce. Bandytów czeka bezlitosna zemsta.",
            popularity: 10.949,
            poster_path: "/tHynkXrurd8qL57fbP5xVpKDh1l.jpg",
            release_date: "2009-11-11",
            title: "Harry Brown",
            video: false,
            vote_average: 6.8,
            vote_count: 662,
          },
          {
            adult: false,
            backdrop_path: "/cXU4zg2aKglQrMOLokHLbnxwkGV.jpg",
            genre_ids: [35, 10749, 18],
            id: 639,
            original_language: "en",
            original_title: "When Harry Met Sally...",
            overview:
              "Historia dwunastoletniego związku dwojga młodych ludzi, których drogi po skończeniu studiów rozchodzą się. Po pięciu latach przypadkowo spotykają się w samolocie. Początkowa niechęć z wolna przeobraża się w przyjaźń. Po wielu wspólnie spędzonych chwilach ciężko jest im stwierdzić czy dalej są tylko przyjaciółmi, czy łączy ich coś więcej.",
            popularity: 17.209,
            poster_path: "/t7vXcgNGnZ8czPov0UkQI7o3QRn.jpg",
            release_date: "1989-01-12",
            title: "Kiedy Harry poznał Sally",
            video: false,
            vote_average: 7.4,
            vote_count: 2709,
          },
          {
            adult: false,
            backdrop_path: "/4LOxoeZWt5wr9mooxEZRFK96lDd.jpg",
            genre_ids: [99],
            id: 483898,
            original_language: "en",
            original_title: "50 Greatest Harry Potter Moments",
            overview: "",
            popularity: 46.37,
            poster_path: "/g1xiBoLD6v3ZaXPa4QtuXiQeYKW.jpg",
            release_date: "2011-07-27",
            title: "50 Greatest Harry Potter Moments",
            video: false,
            vote_average: 7.8,
            vote_count: 22,
          },
          {
            adult: false,
            backdrop_path: "/coJLkvK5KZQoMl8vGqcpgAZYroi.jpg",
            genre_ids: [35, 18],
            id: 2639,
            original_language: "en",
            original_title: "Deconstructing Harry",
            overview: "",
            popularity: 9.837,
            poster_path: "/2ZkTBt5wunAIIEx6UFtxxLdzkKM.jpg",
            release_date: "1997-12-12",
            title: "Przejrzeć Harry'ego",
            video: false,
            vote_average: 7.4,
            vote_count: 532,
          },
          {
            adult: false,
            backdrop_path: "/hNQ0R4wSaXTUPUQti8FtKLf1HQ6.jpg",
            genre_ids: [35, 80, 9648],
            id: 11718,
            original_language: "en",
            original_title: "Who's Harry Crumb?",
            overview:
              "Harry Crumb należy do największej rodziny prywatnych detektywów. Niestety, przez niezdarność został z niej wyrzucony na 10 lat. W tym czasie interes został przejęty przez Eliota Draisena. Gdy Harry powraca, Eliot zleca mu sprawę porwanego dziecka. Robi to, by móc uciec z żoną klienta. Za pomocą przebrań Harry chce rozwiązać sprawę i udowodnić, że należy do rodziny Crumbów.",
            popularity: 9.261,
            poster_path: "/qf7LNguEfBHF9WRs9sKGPBaQYEt.jpg",
            release_date: "1989-02-03",
            title: "Kim jest Harry Crumb?",
            video: false,
            vote_average: 5.7,
            vote_count: 178,
          },
          {
            adult: false,
            backdrop_path: "/71gHxSX2Tzg9mi1VYRdwCECfmpj.jpg",
            genre_ids: [35, 14, 10751],
            id: 8989,
            original_language: "en",
            original_title: "Harry and the Hendersons",
            overview:
              "George, Nancy oraz ich dzieci, Sarah i Ernie, wracają samochodem z wakacji. Przejeżdżając przez las, potrącają na szosie wielkie, kudłate zwierzę. Przekonani, że stworzenie jest martwe, przywożą je do domu, by powiadomić o wypadku nadleśnictwo. Wkrótce okazuje się, że stwór żyje i szybko wraca do sił. Hendersonowie przywiązują się do łagodnej istoty, której nadają imię Harry. Pewnego dnia olbrzym ucieka. W mieście wybucha panika. Hendersonowie próbują za wszelką cenę uratować włochatego przyjaciela, którego ściga myśliwy.",
            popularity: 10.607,
            poster_path: "/7bmtLtiei9WLe8wY8hKk1Smf65z.jpg",
            release_date: "1987-06-05",
            title: "Harry i Hendersonowie",
            video: false,
            vote_average: 5.9,
            vote_count: 426,
          },
          {
            adult: false,
            backdrop_path: "/nKM71iyHoXG2DUBXml0mNwPChvg.jpg",
            genre_ids: [10749, 10770, 35],
            id: 647325,
            original_language: "en",
            original_title: "The Thing About Harry",
            overview: "",
            popularity: 14.686,
            poster_path: "/sdn5NdFMcsub3QUwlovOA9fPJoW.jpg",
            release_date: "2020-02-15",
            title: "The Thing About Harry",
            video: false,
            vote_average: 7.9,
            vote_count: 88,
          },
          {
            adult: false,
            backdrop_path: "/bDqchWjPhko0XvRBx4pErPMk0Hv.jpg",
            genre_ids: [10749],
            id: 518527,
            original_language: "en",
            original_title: "Harry & Meghan: A Royal Romance",
            overview: "",
            popularity: 13.107,
            poster_path: "/2ODzSaM8EKF28mGjNTH3ptb3BJu.jpg",
            release_date: "2018-05-13",
            title: "Harry & Meghan: A Royal Romance",
            video: false,
            vote_average: 6.9,
            vote_count: 150,
          },
          {
            adult: false,
            backdrop_path: "/kagW7NjLnnWzF7BFX8CfNUobQWM.jpg",
            genre_ids: [18, 10749],
            id: 27091,
            original_language: "en",
            original_title: "Harry + Max",
            overview: "",
            popularity: 5.998,
            poster_path: "/nIamsnmqYgRLuosJFlWGiCMXS8A.jpg",
            release_date: "2004-01-17",
            title: "Harry + Max",
            video: false,
            vote_average: 5.6,
            vote_count: 18,
          },
          {
            adult: false,
            backdrop_path: "/eAPj43jprYqhQvqzaP7B1LL7B0N.jpg",
            genre_ids: [12, 35, 18, 10749],
            id: 42448,
            original_language: "en",
            original_title: "Harry and Tonto",
            overview: "",
            popularity: 5.275,
            poster_path: "/5aCrpRRJJBPZ0QqNuMmW2Rzp9FQ.jpg",
            release_date: "1974-08-12",
            title: "Harry and Tonto",
            video: false,
            vote_average: 7.1,
            vote_count: 51,
          },
          {
            adult: false,
            backdrop_path: "/4PHbeHC7q7XJk44TsbAUwDS2rv1.jpg",
            genre_ids: [18],
            id: 91767,
            original_language: "en",
            original_title: "Harry & Son",
            overview:
              "Harry (Paul Newman), mężczyzna w średnim wieku, ma duże problemy z komunikacją ze swym nastoletnim synem, Howardem (Robby Benson). Podczas gdy Harry chce, aby Howard znalazł sobie pracę i zarabiał na swoje życie, wrażliwy chłopak woli wybrać karierę pisarską. Howard stara się przekonac ojca do własnej decyzji, ale dochodzi do wniosku, że musi sam wziąć się za własne życie. W dodatku jego dziewczyna zachodzi w ciążę...",
            popularity: 5.058,
            poster_path: "/kl9yUlWRBEyXNGIXav1WIRBy5te.jpg",
            release_date: "1984-03-02",
            title: "Harry i syn",
            video: false,
            vote_average: 6.1,
            vote_count: 39,
          },
        ],
        total_pages: 22,
        total_results: 434,
      });

      this.get("/filmDetails", {
        adult: false,
        backdrop_path: "/hziiv14OpD73u9gAak4XDDfBKa2.jpg",
        belongs_to_collection: {
          id: 1241,
          name: "Harry Potter - Kolekcja",
          poster_path: "/1GPJWb8ctSHWLn8QvpIFuYv2SG4.jpg",
          backdrop_path: "/wfnMt6LGqYHcNyOfsuusw5lX3bL.jpg",
        },
        budget: 125000000,
        genres: [
          { id: 12, name: "Przygodowy" },
          { id: 14, name: "Fantasy" },
        ],
        homepage:
          "https://www.warnerbros.com/movies/harry-potter-and-sorcerers-stone/",
        id: 671,
        imdb_id: "tt0241527",
        original_language: "en",
        original_title: "Harry Potter and the Philosopher's Stone",
        overview:
          "Harry Potter dowiaduje się, w dniu swoich 11-tych urodzin, że jest osieroconym dzieckiem dwojga potężnych czarodziejów i sam posiada magiczne zdolności. W Szkole Magii i Czarodziejstwa w Hogwarcie przeżywa największą przygodę swojego życia. Uczy się latania na miotle i różnych pożytecznych zaklęć. Przeżywa także chwile grozy rozwiązując zagadkę tajemniczego kamienia filozoficznego i tocząc walkę z potężnym i złym czarodziejem-Lordem Voldermort.",
        popularity: 165.296,
        poster_path: "/wNRk1vec98vfAQa2YdZOt7h0DGe.jpg",
        production_companies: [
          {
            id: 174,
            logo_path: "/ky0xOc5OrhzkZ1N6KyUxacfQsCk.png",
            name: "Warner Bros. Pictures",
            origin_country: "US",
          },
          {
            id: 437,
            logo_path: "/nu20mtwbEIhUNnQ5NXVhHsNknZj.png",
            name: "Heyday Films",
            origin_country: "GB",
          },
          {
            id: 436,
            logo_path: "/A7WCkG3F0NFvjGCwUnclpGdIu9E.png",
            name: "1492 Pictures",
            origin_country: "US",
          },
        ],
        production_countries: [
          { iso_3166_1: "GB", name: "United Kingdom" },
          { iso_3166_1: "US", name: "United States of America" },
        ],
        release_date: "2001-11-16",
        revenue: 976475550,
        runtime: 153,
        spoken_languages: [
          { english_name: "English", iso_639_1: "en", name: "English" },
        ],
        status: "Released",
        tagline: "Podróż poza granice wyobraźni.",
        title: "Harry Potter i Kamień Filozoficzny",
        video: false,
        vote_average: 7.9,
        vote_count: 19389,
      });

      this.get("/filmActors", {
        cast: [
          {
            cast_id: 27,
            character: "Harry Potter",
            credit_id: "52fe4267c3a36847f801be91",
            id: 10980,
            name: "Daniel Radcliffe",
            order: 0,
            profile_path: "/j0A7iK2wIQ1NWwJVVaTegMmKgR.jpg",
            gender: 2,
          },
          {
            cast_id: 37,
            character: "Ron Weasley",
            credit_id: "52fe4267c3a36847f801beb9",
            id: 10989,
            name: "Rupert Grint",
            order: 1,
            profile_path: "/iFlkpTaOF6fGLqxz8b0PhI0i0zN.jpg",
            gender: 2,
          },
          {
            cast_id: 49,
            character: "Hermione Granger",
            credit_id: "531736ea92514138c00010a3",
            id: 10990,
            name: "Emma Watson",
            order: 2,
            profile_path: "/dMbd2Rx9ZD5Gl9VXAkGcIKGrAxJ.jpg",
            gender: 1,
          },
          {
            cast_id: 23,
            character: "Albus Dumbledore",
            credit_id: "52fe4267c3a36847f801be81",
            id: 194,
            name: "Richard Harris",
            order: 3,
            profile_path: "/feNslXF8WLVfpouXyGdKvCYBLht.jpg",
            gender: 2,
          },
          {
            cast_id: 41,
            character: "Draco Malfoy",
            credit_id: "52fe4267c3a36847f801bec9",
            id: 10993,
            name: "Tom Felton",
            order: 4,
            profile_path: "/bg5TcioIqc5Kt6CE609wXziZ9Cm.jpg",
            gender: 2,
          },
          {
            cast_id: 44,
            character: "Severus Snape",
            credit_id: "52fe4267c3a36847f801bed5",
            id: 4566,
            name: "Alan Rickman",
            order: 5,
            profile_path: "/7tADZs4ILE93oJ5pAh6mKQFEq2m.jpg",
            gender: 2,
          },
          {
            cast_id: 25,
            character: "Rubeus Hagrid",
            credit_id: "52fe4267c3a36847f801be89",
            id: 1923,
            name: "Robbie Coltrane",
            order: 6,
            profile_path: "/jOHs3xvlwRiiG2CLtso5zzmGCXg.jpg",
            gender: 2,
          },
          {
            cast_id: 24,
            character: "Minerva McGonagall",
            credit_id: "52fe4267c3a36847f801be85",
            id: 10978,
            name: "Maggie Smith",
            order: 7,
            profile_path: "/pxJSXL9NELIsawroTYNQOt5JlZz.jpg",
            gender: 1,
          },
          {
            cast_id: 30,
            character: "Vernon Dursley",
            credit_id: "52fe4267c3a36847f801be9d",
            id: 10983,
            name: "Richard Griffiths",
            order: 8,
            profile_path: "/3xJvWe2qoWJZUQ3BdWdZdMT4CvB.jpg",
            gender: 2,
          },
          {
            cast_id: 32,
            character: "Professor Quirrell/Voldemort",
            credit_id: "52fe4267c3a36847f801bea5",
            id: 10985,
            name: "Ian Hart",
            order: 9,
            profile_path: "/xMC8aPDwhEZcjRHEFcgytSr3BzM.jpg",
            gender: 2,
          },
          {
            cast_id: 28,
            character: "Petunia Dursley",
            credit_id: "52fe4267c3a36847f801be95",
            id: 10981,
            name: "Fiona Shaw",
            order: 10,
            profile_path: "/imZ9Ad2RIPmxHZjeflF9po4WVfO.jpg",
            gender: 1,
          },
          {
            cast_id: 35,
            character: "Garrick Ollivander",
            credit_id: "52fe4267c3a36847f801beb1",
            id: 5049,
            name: "John Hurt",
            order: 11,
            profile_path: "/99ZZrx3mJZoxqQeJ2oeurwxBlKf.jpg",
            gender: 2,
          },
          {
            cast_id: 53,
            character: "Argus Filch",
            credit_id: "55022362c3a3685bab003478",
            id: 11180,
            name: "David Bradley",
            order: 12,
            profile_path: "/znpkwHitb3pcaJbUmgDqG0YenYp.jpg",
            gender: 2,
          },
          {
            cast_id: 43,
            character: "Neville Longbottom",
            credit_id: "52fe4267c3a36847f801bed1",
            id: 96841,
            name: "Matthew Lewis",
            order: 13,
            profile_path: "/oDF0GxbLmbuZurVwdXvGn8vc78v.jpg",
            gender: 2,
          },
          {
            cast_id: 52,
            character: "Oliver Wood",
            credit_id: "5502218bc3a3685ba6003950",
            id: 11179,
            name: "Sean Biggerstaff",
            order: 14,
            profile_path: "/6g9cQWg3ikD3xboDtyF8qKdpmgl.jpg",
            gender: 2,
          },
          {
            cast_id: 50,
            character: "Goblin Bank Teller / Filius Flitwick",
            credit_id: "54ecf79cc3a3680be60022eb",
            id: 11184,
            name: "Warwick Davis",
            order: 15,
            profile_path: "/vUwjgAYcBEcCv0OVAN00qUUXX3V.jpg",
            gender: 2,
          },
          {
            cast_id: 29,
            character: "Dudley Dursley",
            credit_id: "52fe4267c3a36847f801be99",
            id: 10982,
            name: "Harry Melling",
            order: 16,
            profile_path: "/b0pHwi2MeqxEpeWnF4Llihu53aJ.jpg",
            gender: 2,
          },
          {
            cast_id: 154,
            character: "Fred Weasley",
            credit_id: "58f1c6b29251412fb9004a38",
            id: 96851,
            name: "James Phelps",
            order: 17,
            profile_path: "/qt9VZiasqGxRqbOLgSgoHmOGtoy.jpg",
            gender: 2,
          },
          {
            cast_id: 155,
            character: "George Weasley",
            credit_id: "58f1c6bd9251412fb9004a3f",
            id: 140368,
            name: "Oliver Phelps",
            order: 18,
            profile_path: "/rBRUVl2AZ1oz5TOSJdSKHLDPsB6.jpg",
            gender: 2,
          },
          {
            cast_id: 51,
            character: "Nearly Headless Nick (Sir Nicolas)",
            credit_id: "55021c2a9251413da800389e",
            id: 8930,
            name: "John Cleese",
            order: 19,
            profile_path: "/kg63gNYQtGPi2fSNIvCnVAclCbi.jpg",
            gender: 2,
          },
          {
            cast_id: 40,
            character: "Percy Weasley",
            credit_id: "52fe4267c3a36847f801bec5",
            id: 10992,
            name: "Chris Rankin",
            order: 20,
            profile_path: "/bGrWreM4CeXWLJ7VulJnXoJfSgj.jpg",
            gender: 2,
          },
          {
            cast_id: 152,
            character: "Dean Thomas",
            credit_id: "57b42075c3a3686f6d004933",
            id: 234923,
            name: "Alfred Enoch",
            order: 21,
            profile_path: "/eEVvPHmxRBcEGqtoTujncmwNDhR.jpg",
            gender: 2,
          },
          {
            cast_id: 156,
            character: "Seamus Finnigan",
            credit_id: "58f1c6d89251412fdf00498c",
            id: 234922,
            name: "Devon Murray",
            order: 22,
            profile_path: "/jlwr3uKGgGmcWq06u2eUEerQ3kG.jpg",
            gender: 2,
          },
          {
            cast_id: 157,
            character: "Vincent Crabbe",
            credit_id: "58f1c6f49251412fdf00499c",
            id: 956224,
            name: "Jamie Waylett",
            order: 23,
            profile_path: "/2Eg3ImAsq5c5tNAyJFHcFC1lejf.jpg",
            gender: 2,
          },
          {
            cast_id: 158,
            character: "Gregory Goyle",
            credit_id: "58f1c7019251412ff4004a3b",
            id: 11212,
            name: "Josh Herdman",
            order: 24,
            profile_path: "/hebwDG5XsbfMaEaWJ0X6OrvlXwW.jpg",
            gender: 2,
          },
          {
            cast_id: 45,
            character: "Misses Hooch",
            credit_id: "52fe4267c3a36847f801bed9",
            id: 20240,
            name: "Zoë Wanamaker",
            order: 25,
            profile_path: "/keFC6KG1ewLW0ZaP7YkmLVECRrQ.jpg",
            gender: 1,
          },
          {
            cast_id: 42,
            character: "Molly Weasley",
            credit_id: "52fe4267c3a36847f801becd",
            id: 477,
            name: "Julie Walters",
            order: 26,
            profile_path: "/bCTkV2OUgzbJdQEoCk3GesE4DXq.jpg",
            gender: 1,
          },
          {
            cast_id: 39,
            character: "Ginny Weasley",
            credit_id: "52fe4267c3a36847f801bec1",
            id: 10991,
            name: "Bonnie Wright",
            order: 27,
            profile_path: "/xQGPeaIQ6KJXUFbPPW70xKCR5Ee.jpg",
            gender: 1,
          },
          {
            cast_id: 160,
            character: "Lee Jordan",
            credit_id: "58f1c7379251412fb1004a5a",
            id: 871100,
            name: "Luke Youngblood",
            order: 28,
            profile_path: "/9IAkI7agudRLfX1qX0KQYghihtf.jpg",
            gender: 2,
          },
          {
            cast_id: 34,
            character: "Griphook",
            credit_id: "52fe4267c3a36847f801bead",
            id: 10987,
            name: "Verne Troyer",
            order: 29,
            profile_path: "/42pTYfAt6qeCNoXeLunIOLSkW3U.jpg",
            gender: 2,
          },
          {
            cast_id: 167,
            character: "James Potter",
            credit_id: "58f1c7b29251412ff4004aa3",
            id: 1643,
            name: "Adrian Rawlins",
            order: 30,
            profile_path: "/G0PGZqTjenuVTAQiib4ScU7vAI.jpg",
            gender: 2,
          },
          {
            cast_id: 36,
            character: "Lily Potter",
            credit_id: "52fe4267c3a36847f801beb5",
            id: 10988,
            name: "Geraldine Somerville",
            order: 31,
            profile_path: "/yVV0D1aet5FWEvfildXToOmcvkg.jpg",
            gender: 1,
          },
          {
            cast_id: 153,
            character: "The Fat Lady",
            credit_id: "582600ebc3a368361400b475",
            id: 1220119,
            name: "Elizabeth Spriggs",
            order: 32,
            profile_path: "/l7pJk2IkXlb47QXg8Z8xq2vBjc3.jpg",
            gender: 1,
          },
          {
            cast_id: 205,
            character: "Lord Voldemort",
            credit_id: "5bf9eca80e0a263ab3020c05",
            id: 19903,
            name: "Richard Bremmer",
            order: 33,
            profile_path: "/f6B04svt1I5WWwWWFd6AIu7YAfG.jpg",
            gender: 2,
          },
          {
            cast_id: 169,
            character: "The Grey Lady",
            credit_id: "58f1c7d79251412fa9004a65",
            id: 58778,
            name: "Nina Young",
            order: 34,
            profile_path: "/wHsH06MXZ9KAYAaQBcZnJq8aUfD.jpg",
            gender: 1,
          },
          {
            cast_id: 171,
            character: "The Bloody Barron",
            credit_id: "58f1c8049251412fb1004afa",
            id: 10732,
            name: "Terence Bayler",
            order: 35,
            profile_path: "/ui0sfTzTnum4IkFVrLdpOsUbJDL.jpg",
            gender: 0,
          },
          {
            cast_id: 206,
            character: "Station Guard (uncredited)",
            credit_id: "5bf9edd292514104d201d0a5",
            id: 1815748,
            name: "Harry Taylor",
            order: 36,
            profile_path: "/tJVi0TZbqUxOHHDUaV2eExKyykC.jpg",
            gender: 2,
          },
          {
            cast_id: 207,
            character: "Dimpled Woman on Train (uncredited)",
            credit_id: "5bf9f09392514104cc01cb75",
            id: 1795303,
            name: "Jean Southern",
            order: 37,
            profile_path: "/cdItrlTcghSBIgQO5JHt27OdPbT.jpg",
            gender: 1,
          },
          {
            cast_id: 48,
            character: "The Sorting Hat (voice)",
            credit_id: "52fe4267c3a36847f801bee1",
            id: 10655,
            name: "Leslie Phillips",
            order: 38,
            profile_path: "/c4i7qIuX8adXpW1SC4J3Q7HyUVG.jpg",
            gender: 2,
          },
          {
            cast_id: 170,
            character: "Fat Friar",
            credit_id: "58f1c7e49251412fb5004a31",
            id: 1261131,
            name: "Simon Fisher-Becker",
            order: 39,
            profile_path: "/wt7FOsSF0DDIkQnsiyQbb9G75QG.jpg",
            gender: 2,
          },
          {
            cast_id: 31,
            character: "Tom",
            credit_id: "52fe4267c3a36847f801bea1",
            id: 10984,
            name: "Derek Deadman",
            order: 40,
            profile_path: "/f08j7CcKGKwFsCV6yEhjhb83Vuy.jpg",
            gender: 2,
          },
          {
            cast_id: 168,
            character: "Firenze (voice)",
            credit_id: "58f1c7c8c3a3682e95004317",
            id: 56650,
            name: "Ray Fearon",
            order: 41,
            profile_path: "/ou2cqhqdhfQoKVEBpIh0P3sKZti.jpg",
            gender: 2,
          },
          {
            cast_id: 159,
            character: "Susan Bones",
            credit_id: "58f1c7149251412fc7004a37",
            id: 11183,
            name: "Eleanor Columbus",
            order: 42,
            profile_path: "/jswEVJ4diBj9eEO08hv12ZIK4Tw.jpg",
            gender: 0,
          },
          {
            cast_id: 33,
            character: "Diagon Alley Boy",
            credit_id: "52fe4267c3a36847f801bea9",
            id: 10986,
            name: "Ben Borowiecki",
            order: 43,
            profile_path: "/39dQY6AxPmlzTMad6Sv3AAKKBWy.jpg",
            gender: 0,
          },
          {
            cast_id: 161,
            character: "Angelina Johnson",
            credit_id: "58f1c746c3a3682ede0042ea",
            id: 1796502,
            name: "Danielle Tabor",
            order: 44,
            profile_path: "/j1vSVgSWCizFtdaSOJWCiYeP45M.jpg",
            gender: 1,
          },
          {
            cast_id: 162,
            character: "Alicia Spinnet",
            credit_id: "58f1c75ac3a3682ee20040c5",
            id: 1796505,
            name: "Leilah Sutherland",
            order: 45,
            profile_path: "/gUs00bCZKejc7z8xFT2Q9BEofNX.jpg",
            gender: 1,
          },
          {
            cast_id: 163,
            character: "Katie Bell",
            credit_id: "58f1c768c3a3682ea7004475",
            id: 11185,
            name: "Emily Dale",
            order: 46,
            profile_path: "/tRjOgB4quR623B1BaVYmQFr7W8l.jpg",
            gender: 0,
          },
          {
            cast_id: 165,
            character: "Marcus Flint",
            credit_id: "58f1c79d9251412ff4004a8c",
            id: 1796509,
            name: "Will Theakston",
            order: 47,
            profile_path: "/zFhZw7JUcjVTr9nfobUhkq1pRnZ.jpg",
            gender: 0,
          },
          {
            cast_id: 166,
            character: "Terrence Higgs",
            credit_id: "58f1c7a99251412fb9004af1",
            id: 1796510,
            name: "Scot Fearn",
            order: 48,
            profile_path: "/3kBGRXEJ4KwIrRmgDUebiOxEKFs.jpg",
            gender: 2,
          },
          {
            cast_id: 26,
            character: "Baby Harry Potter (uncredited)",
            credit_id: "52fe4267c3a36847f801be8d",
            id: 10979,
            name: "Saunders Triplets",
            order: 49,
            profile_path: "/jzY4Y34NCh1imUZgFMl5xtYQL8j.jpg",
            gender: 0,
          },
          {
            cast_id: 151,
            character: "Child at Zoo (uncredited)",
            credit_id: "576b0fd7925141382800037c",
            id: 1639982,
            name: "Kieri Kennedy",
            order: 50,
            profile_path: null,
            gender: 1,
          },
          {
            cast_id: 174,
            character: "Augusta Longbottom (uncredited)",
            credit_id: "58f1c966c3a3682ee200422b",
            id: 430776,
            name: "Leila Hoffman",
            order: 53,
            profile_path: "/eI2eL9s2VVMVfmie7xO7jeDcLiM.jpg",
            gender: 1,
          },
          {
            cast_id: 266,
            character: "Hogwarts Schoolgirl (uncredited)",
            credit_id: "5e809ad11d6c5f00141d629a",
            id: 143240,
            name: "Julianne Hough",
            order: 54,
            profile_path: "/wG6eBCjLV2tONWNUHWLdIEOTnoq.jpg",
            gender: 1,
          },
          {
            cast_id: 180,
            character: "Girl in Potion Class (uncredited)",
            credit_id: "58f1cc56c3a3682ece0044a4",
            id: 1462953,
            name: "Zoe Sugg",
            order: 56,
            profile_path: null,
            gender: 1,
          },
          {
            cast_id: 61,
            character: "Goblin (uncredited)",
            credit_id: "567aa42ec3a3685bb90025e8",
            id: 1214513,
            name: "Jimmy Vee",
            order: 59,
            profile_path: "/wggqzE3RjIKh6JaboOuEuIi7lj5.jpg",
            gender: 2,
          },
        ],
        id: 671,
      });
      this.get("searchPeople", [
        {
          score: 34.86133,
          person: {
            id: 172658,
            url: "http://www.tvmaze.com/people/172658/lauren-bush-lauren",
            name: "Lauren Bush Lauren",
            country: {
              name: "United States",
              code: "US",
              timezone: "America/New_York",
            },
            birthday: "1984-06-25T00:00:00",
            deathday: null,
            gender: "Female",
            image: {
              medium:
                "http://static.tvmaze.com/uploads/images/medium_portrait/108/272410.jpg",
              original:
                "http://static.tvmaze.com/uploads/images/original_untouched/108/272410.jpg",
            },
            _links: {
              self: {
                href: "http://api.tvmaze.com/people/172658",
              },
            },
          },
        },
        {
          score: 29.20276,
          person: {
            id: 5028,
            url: "http://www.tvmaze.com/people/5028/lauren-german",
            name: "Lauren German",
            country: {
              name: "United States",
              code: "US",
              timezone: "America/New_York",
            },
            birthday: "1978-11-29T00:00:00",
            deathday: null,
            gender: "Female",
            image: {
              medium:
                "http://static.tvmaze.com/uploads/images/medium_portrait/42/106488.jpg",
              original:
                "http://static.tvmaze.com/uploads/images/original_untouched/42/106488.jpg",
            },
            _links: {
              self: {
                href: "http://api.tvmaze.com/people/5028",
              },
            },
          },
        },
        {
          score: 29.20276,
          person: {
            id: 8140,
            url: "http://www.tvmaze.com/people/8140/lauren-weedman",
            name: "Lauren Weedman",
            country: {
              name: "United States",
              code: "US",
              timezone: "America/New_York",
            },
            birthday: "1969-03-05T00:00:00",
            deathday: null,
            gender: "Female",
            image: {
              medium:
                "http://static.tvmaze.com/uploads/images/medium_portrait/84/211953.jpg",
              original:
                "http://static.tvmaze.com/uploads/images/original_untouched/84/211953.jpg",
            },
            _links: {
              self: {
                href: "http://api.tvmaze.com/people/8140",
              },
            },
          },
        },
        {
          score: 29.20276,
          person: {
            id: 12519,
            url: "http://www.tvmaze.com/people/12519/lauren-stamile",
            name: "Lauren Stamile",
            country: {
              name: "United States",
              code: "US",
              timezone: "America/New_York",
            },
            birthday: "1976-09-12T00:00:00",
            deathday: null,
            gender: "Female",
            image: {
              medium:
                "http://static.tvmaze.com/uploads/images/medium_portrait/1/3422.jpg",
              original:
                "http://static.tvmaze.com/uploads/images/original_untouched/1/3422.jpg",
            },
            _links: {
              self: {
                href: "http://api.tvmaze.com/people/12519",
              },
            },
          },
        },
        {
          score: 29.20276,
          person: {
            id: 13040,
            url: "http://www.tvmaze.com/people/13040/lauren-skirvin",
            name: "Lauren Skirvin",
            country: null,
            birthday: null,
            deathday: null,
            gender: null,
            image: null,
            _links: {
              self: {
                href: "http://api.tvmaze.com/people/13040",
              },
            },
          },
        },
        {
          score: 29.20276,
          person: {
            id: 13549,
            url: "http://www.tvmaze.com/people/13549/lauren-mcneely",
            name: "Lauren McNeely",
            country: null,
            birthday: null,
            deathday: null,
            gender: null,
            image: null,
            _links: {
              self: {
                href: "http://api.tvmaze.com/people/13549",
              },
            },
          },
        },
        {
          score: 29.20276,
          person: {
            id: 16155,
            url: "http://www.tvmaze.com/people/16155/lauren-liem",
            name: "Lauren Liem",
            country: null,
            birthday: null,
            deathday: null,
            gender: null,
            image: null,
            _links: {
              self: {
                href: "http://api.tvmaze.com/people/16155",
              },
            },
          },
        },
        {
          score: 29.20276,
          person: {
            id: 16360,
            url: "http://www.tvmaze.com/people/16360/lauren-melendez",
            name: "Lauren Melendez",
            country: {
              name: "United States",
              code: "US",
              timezone: "America/New_York",
            },
            birthday: "1982-03-15T00:00:00",
            deathday: null,
            gender: "Female",
            image: {
              medium:
                "http://static.tvmaze.com/uploads/images/medium_portrait/152/381182.jpg",
              original:
                "http://static.tvmaze.com/uploads/images/original_untouched/152/381182.jpg",
            },
            _links: {
              self: {
                href: "http://api.tvmaze.com/people/16360",
              },
            },
          },
        },
        {
          score: 29.20276,
          person: {
            id: 17659,
            url: "http://www.tvmaze.com/people/17659/lauren-kelly",
            name: "Lauren Kelly",
            country: null,
            birthday: null,
            deathday: null,
            gender: null,
            image: null,
            _links: {
              self: {
                href: "http://api.tvmaze.com/people/17659",
              },
            },
          },
        },
        {
          score: 29.20276,
          person: {
            id: 18832,
            url: "http://www.tvmaze.com/people/18832/lauren-sharpe",
            name: "Lauren Sharpe",
            country: null,
            birthday: null,
            deathday: null,
            gender: "Female",
            image: {
              medium:
                "http://static.tvmaze.com/uploads/images/medium_portrait/186/465056.jpg",
              original:
                "http://static.tvmaze.com/uploads/images/original_untouched/186/465056.jpg",
            },
            _links: {
              self: {
                href: "http://api.tvmaze.com/people/18832",
              },
            },
          },
        },
      ]);
    },
  });
